name: Deploy Tema su Tophost

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v3

      - name: 🚀 Caricamento file
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # PROVA IL PERCORSO RELATIVO
          server-dir: ./wp-content/themes/solaristheme/
          protocol: ftps
          port: 21
          security: loose
          # Evita di caricare la cronologia di Git
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*
            **/.github*/**