name: Deploy Tema su Tophost

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Prelevo il codice
        uses: actions/checkout@v3

      - name: 🚀 Caricamento file via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /httpdocs/wp-content/themes/solaristheme/
          protocol: ftps
          port: 21
          security: loose
          # Questa opzione aiuta se il server fa i capricci con le cartelle esistenti
          dangerous-clean-slate: false 
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*
            **/.github*/**